### ISSUE TITLE
Scraped Images Contain Watermark Which Makes Them Unusable To Train Models

### ISSUE THREAD

**Issue by Kurry** [tcxxxx/DermNet-imgsCrawler#1]
![07acnepittedscars1](https://user-images.githubusercontent.com/857247/43987096-b7d3fec8-9ce9-11e8-8a34-67dc92f92230.jpg)

**Comment by Kurry** [comment]
I see that they are watermarked at the original source. Closing.

**Comment by tcxxxx** [comment]
Hi Kurry, I think these watermarks won't exert much influence on training, and researchers have been using these images with watermark for experiments. If it is still a concern, you could probably contact DermNet for high-quality images without watermark or try some watermark removal processing :)

**Comment by tcxxxx** [comment]
> I see that they are watermarked at the original source. Closing.

I think these watermarks won't exert much influence on training, and researchers have been using these images with watermark for experiments. If it is still a concern, you could probably contact DermNet for high-quality images without watermark or try some watermark removal processing :)
